### ISSUE TITLE
Using with lastest Channel version

### ISSUE THREAD

**Issue by ericel** [pennlabs/django-rest-live#13]
I get this error, trying to use the plugin with Channels 3.0.4
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behavior is the source of the following dependency conflicts.
django-rest-live 0.4.4 requires channels<3,>=2.0.0, but you have channels 3.0.4 which is incompatible.
```

**Comment by Beenhakker** [comment]
Hi,

I am wondering this as well, since I want to use this project, but doubting to start with Channels 2 or wait for the Channels 3 integration.

Can you give us an idea when the existing PR will be merged?
Why integration for Channels 3 has been paused? Seems like some tests are failing.

Existing PR: https://github.com/pennlabs/django-rest-live/pull/6

**Comment by abhi1693** [comment]
@davish @ArmaanT @kevc528 

Hey guys, this is an awesome contribution to the Django world. Are there any expectations to have channels v3 support in this library anytime soon?

**Comment by davish** [comment]
Hi @abhi1693 @Beenhakker @ericel,

This has been fixed on the master branch! Hopefully will cut a release (`0.6.0`) in the next few days. Cheers!

**Comment by looped-monk** [comment]
@abhi1693 


Hello there ,
Can you kindly let me know what this package is used for ? Does subscriptions & updates imply push notification service or something else entirely ?
